#!/usr/bin/env php
<?php
define('SRC_DIR', dirname(__DIR__));
define('LIB_DIR', SRC_DIR . '/library');
define('LIB_H', SRC_DIR . '/php_cmpp_library.h');
define('PHP_TAG', '<?php');

require __DIR__ . '/functions.php';

$list = require LIB_DIR . '/config.inc';
if (empty($list)) {
    swoole_error('can not read library config');
}
$source_str = $eval_str = '';
foreach ($list as $file) {
    $php_file = LIB_DIR . '/' . $file;
    if (strpos(`/usr/bin/env php -n -l {$php_file} 2>&1`, 'No syntax errors detected') === false) {
        swoole_error("syntax error in file {$php_file}");
    } else {
        swoole_ok("syntax correct in [{$file}]");
    }
    $code = file_get_contents($php_file);
    if ($code === false) {
        swoole_error("can not read file {$file}");
    }
    if (strpos($code, PHP_TAG) !== 0) {
        swoole_error('cmpp library php file must start with "<?php"');
    }

    $name = unCamelize(str_replace(['/', '.php'], ['_', ''], $file));
    // keep line breaks to align line numbers
    $code = rtrim(substr($code, strlen(PHP_TAG)));
    $code = str_replace(['\\', '"', "\n"], ['\\\\', '\\"', "\\n\"\n\""], $code);
    $code = implode("\n" . space(4), explode("\n", $code));
    $filename = "@cmpp-src/library/{$file}";
    $code = "static char* cmpp_library_source_{$name} =\n" . space(4) . "\"{$code}\\n\";\n\n";
    // for CDBGMARK:
    // usage: \s*//\s*CDBGMARK\s*:{raw C things}
    $code = preg_replace('|//\s*CDBGMARK\s*:(.+?)\\\\n"|', "\\0\n\\1", $code);
    // for ALIGN:
    // usage: \s*//\s*CDBGMARK\s*:{raw C things}
    $code = preg_replace_callback('|//\s*ALIGN\+(\d)\\\\n|', function($m){
        $ret = $m[0];
        for($i=0; $i<(int)$m[1]; $i++){
            $ret .= "\\n";
        }
        return $ret;
    }, $code);
    $source_str .= $code;
    $eval_str .= space(8) . "cmpp_eval(cmpp_library_source_{$name}, \"{$filename}\");\n";
}
$source_str = rtrim($source_str);
$eval_str = rtrim($eval_str);

$generator = basename(__FILE__);
$content = <<<PHP
/**
 * Generated by {$generator}, Please DO NOT modify!
 */

{$source_str}

void php_cmpp_load_library();


PHP;

if (file_put_contents(LIB_H, $content) != strlen($content)) {
    swoole_error('Can not write source codes to ' . LIB_H);
}
swoole_success("Generated cmpp php library successfully!");
